spring:
  profile: dev
  autoconfigure:
    exclude: org.springframework.cloud.aws.autoconfigure.context.ContextStackAutoConfiguration
cloud:
  aws:
    region:
      auto: false
      static: ap-south-1